### ISSUE TITLE
no username and password taken from QGIS proxy settings?

### ISSUE THREAD

**Issue by rduivenvoorde** [nextgis/quickmapservices#109] opened 2016-09-19 20:40 UTC
Hi,

I was contacted by somebody who is behind a proxy WITH PASSWORD authentication, and he was asking why my plugin was working and quickmapservices was not...

Looking into the code, I think(!) it is because you do not take/use the username/password from QGIS settings (to be honest, somebody else implemented this part for me in my plugin :-) )

https://github.com/rduivenvoorde/pdokservicesplugin/blob/master/pdokgeocoder.py#L34
vs
https://github.com/nextgis/quickmapservices/blob/master/src/qgis_settings.py

Or am I wrong in this?

**Comment by simgislab** [comment] 2016-12-17 18:53
duplicate of #88

**Closed by simgislab** 2016-12-17 18:53 UTC
