### ISSUE TITLE
QGIS 3.0.1 - icons do not appear - QMS 0.19.6

### ISSUE THREAD

**Issue by pigreco** [nextgis/quickmapservices#158] opened 2018-03-27 09:17 UTC
As soon as QMS is installed on QGIS 3.0.1, icons do not appear, I can only find 'Search QMS' in the panels menu.
win 10 OSGEo4w64

**Comment by alisovenko** [comment] 2018-03-27 11:52
'Search QMS' icon  is located:
1. in main menu bar "Web"
2. on Web Toolbar or Manage Layers Toolbar depending on the plugin settings

**Comment by pigreco** [comment] 2018-03-27 12:18
the two icons do not appear anywhere. :-(
![image](https://user-images.githubusercontent.com/7631137/37966694-881486c0-31c9-11e8-874e-d87dc64618eb.png)

**Comment by pigreco** [comment] 2018-03-31 09:26
I can not make the two icons appear,
to use QMS I have to go to:
layer -> add layer -> QuickmapServices

![image](https://user-images.githubusercontent.com/7631137/38161794-ed5d3888-34d5-11e8-9312-2d603a97e001.png)

**Comment by alisovenko** [comment] 2018-04-02 07:49
Are there no icons on the Web Toolbar or Manage Layers Toolbar in your QGIS?
Like this:
![screenshot from 2018-04-02 10-34-38](https://user-images.githubusercontent.com/5332345/38187940-6b141d2c-3662-11e8-95e7-c8996163a8d5.png)
or
![screenshot from 2018-04-02 10-46-29](https://user-images.githubusercontent.com/5332345/38188130-2771ef44-3663-11e8-8c44-961f73916151.png)

Are these toolbars opened in your QGIS? (In the main menu: View->Toolbars)

**Comment by pigreco** [comment] 2018-04-02 13:55
no, I can not find anywhere.
The only way is: Layer menu -> add layer
as per the previous screenshot.

here's what I see in my QGIS
![image](https://user-images.githubusercontent.com/7631137/38198708-2fb21dac-368e-11e8-9725-14c2f4df51c6.png)

![image](https://user-images.githubusercontent.com/7631137/38198733-3ef9e0ba-368e-11e8-983d-dc4a8cb56320.png)

**Comment by alisovenko** [comment] 2018-04-02 14:34
Please open Manage Layers Toolbar (in the main menu: View->Toolbars->Manage Layers Toolbar).
And make sure that there is no icon in this toolbar. 
![screenshot from 2018-04-02 17-33-01](https://user-images.githubusercontent.com/5332345/38200161-f1c97a68-369b-11e8-9b92-a0506e1477b6.png)

**Comment by pigreco** [comment] 2018-04-02 14:49
wow, found
but it's the old bar !!! :-(

![image](https://user-images.githubusercontent.com/7631137/38200719-b3583626-3695-11e8-9f82-5ddd3c4c75c9.png)

**Comment by simgislab** [comment] 2018-04-03 12:48
@alisovenko if I remember correctly, QGIS3 now has new menu for adding layers which made this toolbar obsolete (?), may be we should not let people move QMS buttons on this toolbar and hide the option

may move somewhere else instead?

**Comment by AndresBarranco** [comment] 2018-04-05 18:06
@pigreco 
layer -> add layer -> QuickmapServices -> Settings
Turn off: Move plugin to”Manage Layers” menu/panel
![qms01](https://user-images.githubusercontent.com/38112370/38383413-1560a52c-38d2-11e8-80ce-1bc94f9a8dc1.png)
QMS will appear in the web menu
![qms02](https://user-images.githubusercontent.com/38112370/38383463-2f2a8bb2-38d2-11e8-9e25-f9707fbf305a.png)

**Comment by simgislab** [comment] 2021-05-19 05:57
closing this as duplicate of #208 

summary https://github.com/nextgis/quickmapservices/issues/208#issuecomment-843732834

**Closed by simgislab** 2021-05-19 05:57 UTC
Labels: feedback needed
