### ISSUE TITLE
Get Contributed Pack Gives Error

### ISSUE THREAD

**Issue by asgharibraheembaloch** [nextgis/quickmapservices#232] opened 2022-03-15 09:46 UTC
![image](https://user-images.githubusercontent.com/46741864/158350950-c48b6ac4-f06b-4b10-aa62-f3e94493bcff.png)

**Comment by simgislab** [comment] 2022-03-15 10:07
duplicate of #231

**Closed by simgislab** 2022-03-15 10:07 UTC
