### ISSUE TITLE
Adding a QMS layer changes destination SRS and not project CRS, which is extremely confusing

### ISSUE THREAD

**Issue by AlisterH** [nextgis/quickmapservices#214] opened 2020-10-21 00:49 UTC
- Start QGIS
- Load some data into the map so you are looking at a map in a normal projected coordinate system.
- Load a quick map services layer.  
- The coordinate system selector in the bottom right will still say the project is in the same coordinate system.  But the Coordinate display is now displaying different coordinates (I'm not sure exactly what system they are in).
- If you save the project and look at the project file in a text editor you'll see the map canvas has had its destination SRS set to EPSG:3857.
- If you want to change the map canvas destination SRS back to match the original coordinate system you need to change the project CRS to something else, and then change it back to the original CRS.  When you do this it appears that the quick map services layer still works correctly.

1.  I'm not sure if the map canvas destination SRS actually needs to be changed when adding a quick map services layer.  Does it?
2.  Assuming it does, wouldn't it be far less confusing to either change it back after loading the layer, or change the project CRS instead of just changing the map canvas destination SRS?

**Comment by AlisterH** [comment] 2020-10-21 01:19
It seems to me that the destination SRS doesn't need to be changed - I can just comment out this line in qgis_map_helpers.py:
````
iface.mapCanvas().setDestinationCrs(TileLayer.CRS_3857)

**Comment by simgislab** [comment] 2021-05-18 19:57
Can't reproduce (understand) it here. Here is my scenario:

1. Start QGIS
2. Load a layer in 4326
3. Coords are in degrees, CRS selector shows 4326
4. Search for Mapnik, add it
5. OSM Standard shows, Coords are in degrees, CRS selector shows 4326

can you be more specific?

I'm using QGIS 3.18.

**Comment by AlisterH** [comment] 2021-05-28 09:26
Unfortunately the Windows screen recorder won't record context menus and dialogs, so I'm not sure it's worth it, but here is a recording showing the coordinate display changing.
The empty memory layer is in EPSG:2193
I load the Google satellite layer then use "set project CRS from layer" to change to EPSG:2193 and back to EPSG:2105.
https://user-images.githubusercontent.com/714600/119962138-d9b24400-bffa-11eb-8de2-13da02bdd199.mp4

**Comment by simgislab** [comment] 2021-05-28 09:39
please check this and may be try to replicate it

http://m-d.me/img/ss/zQz4vpqGC4.gif

does it produce correct behavior for you?

**Comment by AlisterH** [comment] 2021-05-28 10:00
I see - the problem only occurs when I load the layer using the menu Web>Quickmapservices.
There is no problem if I use the "Search QMS" panel to load the layer.

**Comment by simgislab** [comment] 2021-05-28 10:09
that's it then, marking it as a bug

the behavior from the catalog should be the same as behavior from the QMS search

PS: for the future reference, we'll be retiring catalog gradually in favor of search panel

**Comment by AlisterH** [comment] 2021-05-31 05:24
> PS: for the future reference, we'll be retiring catalog gradually in favor of search panel

That's a shame because it's nice to not have to use a panel.

**Comment by simgislab** [comment] 2021-05-31 07:42
no difference, same number of clicks

**Comment by simgislab** [comment] 2021-06-05 13:11
ok, I was to quick to call it a bug.

It's just a option that apparently is turned on for you:

![](http://m-d.me/img/ss/20210605_160751.png)

If you don't like your CRS to change to 3857 on adding a basemap - just turn it off. It should fix everything.

We'll:

* make behavior the same with catalog and search panel
* make sure the option is off by default

**Comment by 514ckw4r3** [comment] 2021-06-07 15:05
Fixed in 0.19.19

**Comment by AlisterH** [comment] 2021-06-07 21:55
Sorry, there is still a bug (or arguably two), it is just different now.
If "Enable EPSG:3857 (OTF) on adding TMS:" setting is disabled, both the menu and the panel work as expected.  But if the setting is enabled:
1. when I add a QMS layer using the menu it doesn't enable EPSG:3857, and
2. when I add a QMS layer using the search panel it has the same problem that I was originally complaining about with the menu.   The Coordinate display now displays a "current map coordinate" that is in EPSG:3857, but the "current CRS" button is the same coordinate system it was before adding the layer.  Surely this is not right - it should say EPSG:3857.

**Comment by simgislab** [comment] 2021-06-09 08:49
did you update to latest version of QMS plugin (0.19.17)?

just tested with this option ON and both scenarios change project CRS to 3857 like expected

**Comment by AlisterH** [comment] 2021-06-09 09:12
0.19.19, and I have just double-checked that the behaviour is as per my last comment.

Also, I checked that after adding the QMS layer using the search panel, the problem isn't just that the "current CRS" button displays the wrong CRS.  QGIS really believes that it is still using the original CRS, e.g. if I use the nominatum location filter to find an address, I get taken to completely the wrong place (the displayed coordinates would be correct for the original CRS).

**Comment by AlisterH** [comment] 2021-06-09 09:20
Testing with a clean QGIS profile the behaviour is the same as I have described.  Interestingly the "Search QMS" panel remembered the "Last used" services from the original profile.

**Comment by simgislab** [comment] 2021-06-09 09:23
Ok, I'm confused. Please try to be very specific and omit any side information such as nominatim usage etc. Stick to the bare scenario.

I'm doing this:

Enable 3857 option in QMS is on.
1. Open new QGIS project, EPSG 4326 is default
2. Search for Mapnik in search panel
3. Add found geoservice
4. Project CRS changes to 3857.

does this work for you?

**Comment by AlisterH** [comment] 2021-06-09 10:18
That only works if I start with a new empty project _and with QGIS itself configured to change the CRS to match the first layer added_ (Scenario B below).  Scenario C below demonstrates the problem.

Scenario A:
"Settings>Options>CRS for Projects>When a new project is created" is set to **"Use CRS from first layer added"**, and "Enable EPSG:3857 (OTF) on adding TMS" is **OFF**.
I follow your steps 1 to 3 and the CRS is changed to EPSG:3857, presumably because of the QGIS setting.
This behaviour seems correct.

Scenario B:
"Settings>Options>CRS for Projects>When a new project is created" is set to **"Use CRS from first layer added"**, and "Enable EPSG:3857 (OTF) on adding TMS" is **ON**.
I follow your steps 1 to 3 and the CRS is changed to EPSG:3857.
This behaviour seems correct.

Scenario C:
"Settings>Options>CRS for Projects>When a new project is created" is set to **"Use a default CRS"**, and "Enable EPSG:3857 (OTF) on adding TMS" is **ON**.
I follow your steps 1 to 3 and the map and coordinates display in EPSG:3857 (correct behaviour), but the "current CRS" button still says the CRS is EPSG:4326 (incorrect behaviour).

Scenario D:
"Settings>Options>CRS for Projects>When a new project is created" is set to **"Use a default CRS"**, and "Enable EPSG:3857 (OTF) on adding TMS" is **ON**.
I follow your steps 1 to 3 and the map and coordinates display in EPSG:4326 (correct behaviour).

**Comment by AlisterH** [comment] 2021-06-09 10:20
Sorry, fixed my description of scenario D.

**Comment by simgislab** [comment] 2021-06-09 10:28
thanks so much for working on that, now it is clear

@514ckw4r3 lets work on Scenario C below, I believe we should override QGIS setting in this case and boil down Scenario C to Scenario B

**Comment by 514ckw4r3** [comment] 2021-06-09 11:36
@AlisterH, the setting "CMS for Projects->When a new project is created" only affects new projects. You need to create a new project and then the Project CRS will be set correctly.

**Comment by AlisterH** [comment] 2021-06-09 12:33
?
That setting works fine, I don't know why you think I have a problem with it.  The problem is with the QMS setting.

**Comment by AlisterH** [comment] 2021-06-09 12:44
> I believe we should override QGIS setting in this case and boil down Scenario C to Scenario B

Note that the issue is actually unrelated to the initial setting of a project CRS - the QMS layer would usually not be the first layer added.

**Comment by AlisterH** [comment] 2021-06-09 13:10
Personally I don't understand why QMS needs this setting - people don't normally seem to need the CRS changed every time a new layer is added, so I'm not sure why they would need that when using QMS.  I imagine your code would be a lot simpler without this option...

**Comment by simgislab** [comment] 2021-06-09 13:22
good question, we've been discussing to remove it altogether too

**Comment by simgislab** [comment] 2021-06-09 13:24
the current plan is to first fix Scenario C to make behavior consistent and then rethink it completely may be removing settings altogether

**Comment by 514ckw4r3** [comment] 2021-06-09 15:32
Scenario C fixed in version 0.19.20. Now the 'Enable EPSG:3857 (OTF) on adding TMS' option also changes the project CRS. The fix will be available in the next release.

**Comment by AlisterH** [comment] 2021-06-09 21:14
OK, that works properly when adding from the search panel
But please be aware that it doesn't attempt to enable EPSG:3857 when adding from the menu.

**Comment by simgislab** [comment] 2021-06-10 02:20
behavior should be the same

**Closed** 2021-06-10 08:49 UTC
Labels: enhancement
