### ISSUE TITLE
The CONTRIBUTE_ZIP_DIRECT_URL is not available

### ISSUE THREAD

**Issue by liuxsdev** [nextgis/quickmapservices#230] opened 2022-03-14 02:17 UTC
CONTRIBUTE_ZIP_DIRECT_URL is set to http://nextgis.ru/programs/qms/quickmapservices_contrib.zip
and It looks like something wrong with this page

![image](https://user-images.githubusercontent.com/11004456/158093281-e390faed-98fe-4f11-b341-6e169402509c.png)

**Comment by simgislab** [comment] 2022-03-15 09:08
yes, we'll fix that

**Comment by simgislab** [comment] 2022-03-15 09:08
duplicate of https://github.com/nextgis/quickmapservices/issues/226

**Closed by simgislab** 2022-03-15 09:08 UTC
